### ISSUE TITLE
Error running ./init.py

### ISSUE THREAD

**Issue by bastien8060** [bastien8060/covid19-prediction#1]
`Init.py ireland` leaves:

```
Traceback (most recent call last):
  File "./init.py", line 3, in <module>
    from statsmodels.tsa.ar_model import AR
  File "/usr/local/lib/python2.7/dist-packages/statsmodels/tsa/__init__.py", line 1, in <module>
    from statsmodels.tools._testing import PytestTester
  File "/usr/local/lib/python2.7/dist-packages/statsmodels/tools/__init__.py", line 1, in <module>
    from .tools import add_constant, categorical
  File "/usr/local/lib/python2.7/dist-packages/statsmodels/tools/tools.py", line 8, in <module>
    from statsmodels.compat.python import lzip, lmap
  File "/usr/local/lib/python2.7/dist-packages/statsmodels/compat/__init__.py", line 1, in <module>
    from statsmodels.tools._testing import PytestTester
  File "/usr/local/lib/python2.7/dist-packages/statsmodels/tools/_testing.py", line 11, in <module>
    from statsmodels.compat.pandas import assert_equal
  File "/usr/local/lib/python2.7/dist-packages/statsmodels/compat/pandas.py", line 4, in <module>
    import numpy as np
  File "/usr/local/lib/python2.7/dist-packages/statsmodels/compat/numpy.py", line 46, in <module>
    NP_LT_114 = LooseVersion(np.__version__) < LooseVersion('1.14')
AttributeError: 'module' object has no attribute '__version__'

```
Happens on python 2.7 with Debian.

**Comment by bastien8060** [comment]
Issue fixed. Script is now using Python 3.
